import 'package:flutter/material.dart';
const activeCardColor = Color(0xFF1D1E33);
const inActiveCardColor = Color(0xFF111328);
const bottomContainerHeight = 80.0;
const bottomContainerColor = Color(0xFFEB1555);
const labelTextStyle=TextStyle(color: Color(0xFF8D8E98),fontSize: 18);
const NumberTextStyle=TextStyle(fontSize: 50,fontWeight: FontWeight.w900);
const ResultsTitleStyle=TextStyle(fontWeight: FontWeight.w900, fontSize: 30);
const WeightTextStyle=TextStyle(fontSize: 80,fontWeight: FontWeight.w900);
const ContainerTextStyle=TextStyle(fontSize: 30, fontWeight: FontWeight.w900);